const instances = [
    'https://pipedapi.kavin.rocks',
    'https://api.piped.yt',
    'https://pipedapi.drgns.space',
    'https://api.piped.privacy.com.de'
];

async function testPiped(videoId) {
    try {
        console.log('Checking connectivity to google.com...');
        await fetch('https://www.google.com');
        console.log('Connectivity OK.');
    } catch (e) {
        console.error('Connectivity check failed:', e.message);
    }

    console.log(`Testing Piped API for video ID: ${videoId}`);

    for (const baseUrl of instances) {
        console.log(`\nUsing instance: ${baseUrl}`);
        try {
            const response = await fetch(`${baseUrl}/streams/${videoId}`);
            if (!response.ok) {
                console.log(`Instance failed with status: ${response.status}`);
                continue;
            }
            const data = await response.json();

            if (!data.subtitles || data.subtitles.length === 0) {
                console.log('No subtitles found in response.');
                continue;
            }

            console.log(`Success! Found ${data.subtitles.length} subtitle tracks.`);

            // Find English
            const enSubtitle = data.subtitles.find(s => s.code === 'en' || s.name === 'English' || s.autoGenerated);

            if (enSubtitle) {
                console.log('Found English subtitle:', enSubtitle);
                console.log('Fetching subtitle content from:', enSubtitle.url);

                const subResponse = await fetch(enSubtitle.url);
                const subText = await subResponse.text();

                console.log('Subtitle content preview:');
                console.log(subText.substring(0, 500));
                return; // Success, stop trying
            } else {
                console.log('No English subtitle found. First available:', data.subtitles[0]);
            }

        } catch (error) {
            console.error(`Instance ${baseUrl} failed:`, error.message);
        }
    }
    console.log('All instances failed.');
}

testPiped('1HalL6d2gqQ');
